# Generated by Django 5.1.3 on 2024-11-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='card_number',
            field=models.CharField(max_length=19),
        ),
    ]
