# Generated by Django 5.1.3 on 2024-11-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customformtemplate_userprofile_form_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
