# Generated by Django 5.1.3 on 2024-12-13 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_display_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTemplateAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customformtemplate')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_access', to='core.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'template')},
            },
        ),
    ]
