# Generated by Django 5.1.3 on 2024-12-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usertemplateaccess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTemplateAccess',
        ),
    ]
