# Generated by Django 5.1.3 on 2024-11-23 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_weeks', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
